#!/bin/bash

#check for root
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
        echo "Config must be run as root"
            exit
        fi

#install bleachbit garbage collector
apt-get install bleachbit -y --force-yes

#disable mail logging
sed -i '/\/var\/log\/mail/d' /etc/rsyslog.d/50-default.conf

#enable maildir instead of mbox
postconf -e "mail_spool_directory = /var/spool/mail/"

#make sure procmail isn't being used
postconf -e "mailbox_command = "
