#!/bin/bash

#check for root
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
        echo "Not running as root"
            exit
        fi

#install bleachbit garbage collector
apt-get install bleachbit -y --force-yes

#disable mail logging
sed -i '/\/var\/log\/mail/d' /etc/rsyslog.d/50-default.conf
